apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anycast-origin.fullname" . }}
  labels:
    {{- include "anycast-origin.labels" . | nindent 4 }}
spec:
  {{- if .Values.identity.pvc.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "anycast-origin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        # Roll deployment on config change
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "anycast-origin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anycast-origin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/anycast-origin
          args:
            - -config=/etc/anycast/config/origin_config.json
            - -manifest=/etc/anycast/secrets/origin_manifest.pb
            - -ca-pub=/etc/anycast/secrets/ca.pub
            {{- if .Values.identity.pvc.enabled }}
            - -identity-key=/var/lib/anycast/identity/identity.key
            {{- else }}
            - -identity-key=/etc/anycast/secrets/identity.key
            {{- end }}
            - -master-key-file=/etc/anycast/secrets/master.key
          volumeMounts:
            - name: anycast-config
              mountPath: /etc/anycast/config
              readOnly: true
            - name: anycast-secrets
              mountPath: /etc/anycast/secrets
              readOnly: true
            {{- if .Values.identity.pvc.enabled }}
            - name: identity-storage
              mountPath: /var/lib/anycast/identity
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: anycast-config
          configMap:
            name: {{ include "anycast-origin.fullname" . }}-config
        - name: anycast-secrets
          secret:
            secretName: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ include "anycast-origin.fullname" . }}-secrets{{ end }}
        {{- if .Values.identity.pvc.enabled }}
        - name: identity-storage
          persistentVolumeClaim:
            claimName: {{ if .Values.identity.pvc.existingClaim }}{{ .Values.identity.pvc.existingClaim }}{{ else }}{{ include "anycast-origin.fullname" . }}-identity{{ end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
