{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anycast-edge.fullname" . }}-secrets
  labels:
    {{- include "anycast-edge.labels" . | nindent 4 }}
type: Opaque
data:
  ca.pub: {{ .Values.secrets.caPub | b64enc | quote }}
  edge_manifest.pb: {{ .Values.secrets.manifestBase64 | quote }}
  identity.key: {{ .Values.secrets.identityKey | b64enc | quote }}
{{- end }}
