// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportProtocol int32

const (
	TransportProtocol_PROTOCOL_UNSPECIFIED TransportProtocol = 0
	TransportProtocol_TCP                  TransportProtocol = 1
	TransportProtocol_UDP                  TransportProtocol = 2
	TransportProtocol_TCP_AND_UDP          TransportProtocol = 3
)

// Enum value maps for TransportProtocol.
var (
	TransportProtocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "TCP",
		2: "UDP",
		3: "TCP_AND_UDP",
	}
	TransportProtocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"TCP":                  1,
		"UDP":                  2,
		"TCP_AND_UDP":          3,
	}
)

func (x TransportProtocol) Enum() *TransportProtocol {
	p := new(TransportProtocol)
	*p = x
	return p
}

func (x TransportProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (TransportProtocol) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x TransportProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportProtocol.Descriptor instead.
func (TransportProtocol) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type RoutingPolicy int32

const (
	RoutingPolicy_CLUSTERED_RTT    RoutingPolicy = 0 // RTT-optimized active/active across origins
	RoutingPolicy_TLS_SNI          RoutingPolicy = 1 // Demux shared port via RFC 6066 SNI
	RoutingPolicy_FAILOVER_STANDBY RoutingPolicy = 2 // Primary/Backup promotion on lease timeout
	RoutingPolicy_STRICT_SINGLETON RoutingPolicy = 3 // Fails closed on origin loss. Absolutely NO fallback.
)

// Enum value maps for RoutingPolicy.
var (
	RoutingPolicy_name = map[int32]string{
		0: "CLUSTERED_RTT",
		1: "TLS_SNI",
		2: "FAILOVER_STANDBY",
		3: "STRICT_SINGLETON",
	}
	RoutingPolicy_value = map[string]int32{
		"CLUSTERED_RTT":    0,
		"TLS_SNI":          1,
		"FAILOVER_STANDBY": 2,
		"STRICT_SINGLETON": 3,
	}
)

func (x RoutingPolicy) Enum() *RoutingPolicy {
	p := new(RoutingPolicy)
	*p = x
	return p
}

func (x RoutingPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (RoutingPolicy) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x RoutingPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingPolicy.Descriptor instead.
func (RoutingPolicy) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_ANNOUNCE  MessageType = 0
	MessageType_HEARTBEAT MessageType = 1
	MessageType_REVOKE    MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "ANNOUNCE",
		1: "HEARTBEAT",
		2: "REVOKE",
	}
	MessageType_value = map[string]int32{
		"ANNOUNCE":  0,
		"HEARTBEAT": 1,
		"REVOKE":    2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

type ServiceRegistration struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=p2panycast.control.v1.MessageType" json:"type,omitempty"`
	BindingId            []byte                 `protobuf:"bytes,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"` // 16-byte deterministic BLAKE3 token
	ServiceId            string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // Human-readable identifier (e.g., "pbx-core")
	OriginPeerId         string                 `protobuf:"bytes,4,opt,name=origin_peer_id,json=originPeerId,proto3" json:"origin_peer_id,omitempty"`
	Protocol             TransportProtocol      `protobuf:"varint,5,opt,name=protocol,proto3,enum=p2panycast.control.v1.TransportProtocol" json:"protocol,omitempty"`
	PublicPort           uint32                 `protobuf:"varint,6,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"` // Requested public port on the Edge
	Policy               RoutingPolicy          `protobuf:"varint,7,opt,name=policy,proto3,enum=p2panycast.control.v1.RoutingPolicy" json:"policy,omitempty"`
	SniHostname          string                 `protobuf:"bytes,8,opt,name=sni_hostname,json=sniHostname,proto3" json:"sni_hostname,omitempty"`                               // Required if policy == TLS_SNI
	LeaseDurationSec     uint32                 `protobuf:"varint,9,opt,name=lease_duration_sec,json=leaseDurationSec,proto3" json:"lease_duration_sec,omitempty"`             // Soft-state lease TTL (default: 60)
	LeaseEpoch           uint64                 `protobuf:"varint,10,opt,name=lease_epoch,json=leaseEpoch,proto3" json:"lease_epoch,omitempty"`                                // Fencing token for STRICT_SINGLETON
	EnableProxyProtocol  bool                   `protobuf:"varint,11,opt,name=enable_proxy_protocol,json=enableProxyProtocol,proto3" json:"enable_proxy_protocol,omitempty"`   // TCP: Inject PROXYv2 binary header
	OriginHmacCapability []byte                 `protobuf:"bytes,12,opt,name=origin_hmac_capability,json=originHmacCapability,proto3" json:"origin_hmac_capability,omitempty"` // 16-byte HMAC preventing token swapping
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServiceRegistration) Reset() {
	*x = ServiceRegistration{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistration) ProtoMessage() {}

func (x *ServiceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistration.ProtoReflect.Descriptor instead.
func (*ServiceRegistration) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRegistration) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ANNOUNCE
}

func (x *ServiceRegistration) GetBindingId() []byte {
	if x != nil {
		return x.BindingId
	}
	return nil
}

func (x *ServiceRegistration) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceRegistration) GetOriginPeerId() string {
	if x != nil {
		return x.OriginPeerId
	}
	return ""
}

func (x *ServiceRegistration) GetProtocol() TransportProtocol {
	if x != nil {
		return x.Protocol
	}
	return TransportProtocol_PROTOCOL_UNSPECIFIED
}

func (x *ServiceRegistration) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *ServiceRegistration) GetPolicy() RoutingPolicy {
	if x != nil {
		return x.Policy
	}
	return RoutingPolicy_CLUSTERED_RTT
}

func (x *ServiceRegistration) GetSniHostname() string {
	if x != nil {
		return x.SniHostname
	}
	return ""
}

func (x *ServiceRegistration) GetLeaseDurationSec() uint32 {
	if x != nil {
		return x.LeaseDurationSec
	}
	return 0
}

func (x *ServiceRegistration) GetLeaseEpoch() uint64 {
	if x != nil {
		return x.LeaseEpoch
	}
	return 0
}

func (x *ServiceRegistration) GetEnableProxyProtocol() bool {
	if x != nil {
		return x.EnableProxyProtocol
	}
	return false
}

func (x *ServiceRegistration) GetOriginHmacCapability() []byte {
	if x != nil {
		return x.OriginHmacCapability
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x15p2panycast.control.v1\"\xb2\x04\n" +
	"\x13ServiceRegistration\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".p2panycast.control.v1.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\fR\tbindingId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12$\n" +
	"\x0eorigin_peer_id\x18\x04 \x01(\tR\foriginPeerId\x12D\n" +
	"\bprotocol\x18\x05 \x01(\x0e2(.p2panycast.control.v1.TransportProtocolR\bprotocol\x12\x1f\n" +
	"\vpublic_port\x18\x06 \x01(\rR\n" +
	"publicPort\x12<\n" +
	"\x06policy\x18\a \x01(\x0e2$.p2panycast.control.v1.RoutingPolicyR\x06policy\x12!\n" +
	"\fsni_hostname\x18\b \x01(\tR\vsniHostname\x12,\n" +
	"\x12lease_duration_sec\x18\t \x01(\rR\x10leaseDurationSec\x12\x1f\n" +
	"\vlease_epoch\x18\n" +
	" \x01(\x04R\n" +
	"leaseEpoch\x122\n" +
	"\x15enable_proxy_protocol\x18\v \x01(\bR\x13enableProxyProtocol\x124\n" +
	"\x16origin_hmac_capability\x18\f \x01(\fR\x14originHmacCapability*P\n" +
	"\x11TransportProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\x0f\n" +
	"\vTCP_AND_UDP\x10\x03*[\n" +
	"\rRoutingPolicy\x12\x11\n" +
	"\rCLUSTERED_RTT\x10\x00\x12\v\n" +
	"\aTLS_SNI\x10\x01\x12\x14\n" +
	"\x10FAILOVER_STANDBY\x10\x02\x12\x14\n" +
	"\x10STRICT_SINGLETON\x10\x03*6\n" +
	"\vMessageType\x12\f\n" +
	"\bANNOUNCE\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\n" +
	"\n" +
	"\x06REVOKE\x10\x02B'Z%p2p-anycast/pkg/proto/control;controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_control_proto_goTypes = []any{
	(TransportProtocol)(0),      // 0: p2panycast.control.v1.TransportProtocol
	(RoutingPolicy)(0),          // 1: p2panycast.control.v1.RoutingPolicy
	(MessageType)(0),            // 2: p2panycast.control.v1.MessageType
	(*ServiceRegistration)(nil), // 3: p2panycast.control.v1.ServiceRegistration
}
var file_control_proto_depIdxs = []int32{
	2, // 0: p2panycast.control.v1.ServiceRegistration.type:type_name -> p2panycast.control.v1.MessageType
	0, // 1: p2panycast.control.v1.ServiceRegistration.protocol:type_name -> p2panycast.control.v1.TransportProtocol
	1, // 2: p2panycast.control.v1.ServiceRegistration.policy:type_name -> p2panycast.control.v1.RoutingPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
