// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_EDGE_ROUTER      NodeRole = 1
	NodeRole_ORIGIN_NODE      NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "EDGE_ROUTER",
		2: "ORIGIN_NODE",
	}
	NodeRole_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"EDGE_ROUTER":      1,
		"ORIGIN_NODE":      2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_identity_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_proto_identity_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{0}
}

type AuthorizedPolicy int32

const (
	AuthorizedPolicy_POLICY_CLUSTERED_RTT    AuthorizedPolicy = 0
	AuthorizedPolicy_POLICY_TLS_SNI          AuthorizedPolicy = 1
	AuthorizedPolicy_POLICY_FAILOVER_STANDBY AuthorizedPolicy = 2
	AuthorizedPolicy_POLICY_STRICT_SINGLETON AuthorizedPolicy = 3
)

// Enum value maps for AuthorizedPolicy.
var (
	AuthorizedPolicy_name = map[int32]string{
		0: "POLICY_CLUSTERED_RTT",
		1: "POLICY_TLS_SNI",
		2: "POLICY_FAILOVER_STANDBY",
		3: "POLICY_STRICT_SINGLETON",
	}
	AuthorizedPolicy_value = map[string]int32{
		"POLICY_CLUSTERED_RTT":    0,
		"POLICY_TLS_SNI":          1,
		"POLICY_FAILOVER_STANDBY": 2,
		"POLICY_STRICT_SINGLETON": 3,
	}
)

func (x AuthorizedPolicy) Enum() *AuthorizedPolicy {
	p := new(AuthorizedPolicy)
	*p = x
	return p
}

func (x AuthorizedPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizedPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_identity_proto_enumTypes[1].Descriptor()
}

func (AuthorizedPolicy) Type() protoreflect.EnumType {
	return &file_proto_identity_proto_enumTypes[1]
}

func (x AuthorizedPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizedPolicy.Descriptor instead.
func (AuthorizedPolicy) EnumDescriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{1}
}

type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{0}
}

func (x *PortRange) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PortRange) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type ServiceCapability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServicePattern  string                 `protobuf:"bytes,1,opt,name=service_pattern,json=servicePattern,proto3" json:"service_pattern,omitempty"` // Wildcard glob: "pbx-*", "mc-smp"
	AllowedPolicies []AuthorizedPolicy     `protobuf:"varint,2,rep,packed,name=allowed_policies,json=allowedPolicies,proto3,enum=p2panycast.identity.v1.AuthorizedPolicy" json:"allowed_policies,omitempty"`
	AllowedPorts    []*PortRange           `protobuf:"bytes,3,rep,name=allowed_ports,json=allowedPorts,proto3" json:"allowed_ports,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceCapability) Reset() {
	*x = ServiceCapability{}
	mi := &file_proto_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCapability) ProtoMessage() {}

func (x *ServiceCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCapability.ProtoReflect.Descriptor instead.
func (*ServiceCapability) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceCapability) GetServicePattern() string {
	if x != nil {
		return x.ServicePattern
	}
	return ""
}

func (x *ServiceCapability) GetAllowedPolicies() []AuthorizedPolicy {
	if x != nil {
		return x.AllowedPolicies
	}
	return nil
}

func (x *ServiceCapability) GetAllowedPorts() []*PortRange {
	if x != nil {
		return x.AllowedPorts
	}
	return nil
}

type IdentityClaims struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber uint64                 `protobuf:"varint,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	IssuerId     string                 `protobuf:"bytes,2,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SubjectId    string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Role         NodeRole               `protobuf:"varint,4,opt,name=role,proto3,enum=p2panycast.identity.v1.NodeRole" json:"role,omitempty"`
	// field 5 reserved (was subject_mldsa_pubkey)
	Libp2PPeerId  string               `protobuf:"bytes,6,opt,name=libp2p_peer_id,json=libp2pPeerId,proto3" json:"libp2p_peer_id,omitempty"` // Base58-encoded libp2p Peer ID (derived from node's anchor key)
	NotBefore     int64                `protobuf:"varint,7,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`           // Unix timestamp (seconds)
	NotAfter      int64                `protobuf:"varint,8,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`              // Unix timestamp (seconds)
	Capabilities  []*ServiceCapability `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityClaims) Reset() {
	*x = IdentityClaims{}
	mi := &file_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityClaims) ProtoMessage() {}

func (x *IdentityClaims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityClaims.ProtoReflect.Descriptor instead.
func (*IdentityClaims) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityClaims) GetSerialNumber() uint64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *IdentityClaims) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *IdentityClaims) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *IdentityClaims) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_ROLE_UNSPECIFIED
}

func (x *IdentityClaims) GetLibp2PPeerId() string {
	if x != nil {
		return x.Libp2PPeerId
	}
	return ""
}

func (x *IdentityClaims) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *IdentityClaims) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *IdentityClaims) GetCapabilities() []*ServiceCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SignedCapabilityManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimsPayload []byte                 `protobuf:"bytes,1,opt,name=claims_payload,json=claimsPayload,proto3" json:"claims_payload,omitempty"` // Deterministic Protobuf bytes of IdentityClaims
	CaSignature   []byte                 `protobuf:"bytes,2,opt,name=ca_signature,json=caSignature,proto3" json:"ca_signature,omitempty"`       // ML-DSA-87 signature from Root CA
	CaKeyId       []byte                 `protobuf:"bytes,3,opt,name=ca_key_id,json=caKeyId,proto3" json:"ca_key_id,omitempty"`                 // 32-byte SHA-256 hash of CA pubkey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCapabilityManifest) Reset() {
	*x = SignedCapabilityManifest{}
	mi := &file_proto_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCapabilityManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCapabilityManifest) ProtoMessage() {}

func (x *SignedCapabilityManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCapabilityManifest.ProtoReflect.Descriptor instead.
func (*SignedCapabilityManifest) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{3}
}

func (x *SignedCapabilityManifest) GetClaimsPayload() []byte {
	if x != nil {
		return x.ClaimsPayload
	}
	return nil
}

func (x *SignedCapabilityManifest) GetCaSignature() []byte {
	if x != nil {
		return x.CaSignature
	}
	return nil
}

func (x *SignedCapabilityManifest) GetCaKeyId() []byte {
	if x != nil {
		return x.CaKeyId
	}
	return nil
}

// AuthHello is sent by the connecting node (Origin) to open mutual auth.
type AuthHello struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Manifest      *SignedCapabilityManifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthHello) Reset() {
	*x = AuthHello{}
	mi := &file_proto_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHello) ProtoMessage() {}

func (x *AuthHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHello.ProtoReflect.Descriptor instead.
func (*AuthHello) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{4}
}

func (x *AuthHello) GetManifest() *SignedCapabilityManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// AuthResponse is sent back by the receiving node (Edge) to complete mutual auth.
type AuthResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Manifest      *SignedCapabilityManifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetManifest() *SignedCapabilityManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_proto_identity_proto protoreflect.FileDescriptor

const file_proto_identity_proto_rawDesc = "" +
	"\n" +
	"\x14proto/identity.proto\x12\x16p2panycast.identity.v1\"3\n" +
	"\tPortRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"\xd9\x01\n" +
	"\x11ServiceCapability\x12'\n" +
	"\x0fservice_pattern\x18\x01 \x01(\tR\x0eservicePattern\x12S\n" +
	"\x10allowed_policies\x18\x02 \x03(\x0e2(.p2panycast.identity.v1.AuthorizedPolicyR\x0fallowedPolicies\x12F\n" +
	"\rallowed_ports\x18\x03 \x03(\v2!.p2panycast.identity.v1.PortRangeR\fallowedPorts\"\xd8\x02\n" +
	"\x0eIdentityClaims\x12#\n" +
	"\rserial_number\x18\x01 \x01(\x04R\fserialNumber\x12\x1b\n" +
	"\tissuer_id\x18\x02 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x124\n" +
	"\x04role\x18\x04 \x01(\x0e2 .p2panycast.identity.v1.NodeRoleR\x04role\x12$\n" +
	"\x0elibp2p_peer_id\x18\x06 \x01(\tR\flibp2pPeerId\x12\x1d\n" +
	"\n" +
	"not_before\x18\a \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\b \x01(\x03R\bnotAfter\x12M\n" +
	"\fcapabilities\x18\t \x03(\v2).p2panycast.identity.v1.ServiceCapabilityR\fcapabilities\"\x80\x01\n" +
	"\x18SignedCapabilityManifest\x12%\n" +
	"\x0eclaims_payload\x18\x01 \x01(\fR\rclaimsPayload\x12!\n" +
	"\fca_signature\x18\x02 \x01(\fR\vcaSignature\x12\x1a\n" +
	"\tca_key_id\x18\x03 \x01(\fR\acaKeyId\"Y\n" +
	"\tAuthHello\x12L\n" +
	"\bmanifest\x18\x01 \x01(\v20.p2panycast.identity.v1.SignedCapabilityManifestR\bmanifest\"\\\n" +
	"\fAuthResponse\x12L\n" +
	"\bmanifest\x18\x01 \x01(\v20.p2panycast.identity.v1.SignedCapabilityManifestR\bmanifest*B\n" +
	"\bNodeRole\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vEDGE_ROUTER\x10\x01\x12\x0f\n" +
	"\vORIGIN_NODE\x10\x02*z\n" +
	"\x10AuthorizedPolicy\x12\x18\n" +
	"\x14POLICY_CLUSTERED_RTT\x10\x00\x12\x12\n" +
	"\x0ePOLICY_TLS_SNI\x10\x01\x12\x1b\n" +
	"\x17POLICY_FAILOVER_STANDBY\x10\x02\x12\x1b\n" +
	"\x17POLICY_STRICT_SINGLETON\x10\x03B)Z'p2p-anycast/pkg/proto/identity;identityb\x06proto3"

var (
	file_proto_identity_proto_rawDescOnce sync.Once
	file_proto_identity_proto_rawDescData []byte
)

func file_proto_identity_proto_rawDescGZIP() []byte {
	file_proto_identity_proto_rawDescOnce.Do(func() {
		file_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_identity_proto_rawDesc), len(file_proto_identity_proto_rawDesc)))
	})
	return file_proto_identity_proto_rawDescData
}

var file_proto_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_identity_proto_goTypes = []any{
	(NodeRole)(0),                    // 0: p2panycast.identity.v1.NodeRole
	(AuthorizedPolicy)(0),            // 1: p2panycast.identity.v1.AuthorizedPolicy
	(*PortRange)(nil),                // 2: p2panycast.identity.v1.PortRange
	(*ServiceCapability)(nil),        // 3: p2panycast.identity.v1.ServiceCapability
	(*IdentityClaims)(nil),           // 4: p2panycast.identity.v1.IdentityClaims
	(*SignedCapabilityManifest)(nil), // 5: p2panycast.identity.v1.SignedCapabilityManifest
	(*AuthHello)(nil),                // 6: p2panycast.identity.v1.AuthHello
	(*AuthResponse)(nil),             // 7: p2panycast.identity.v1.AuthResponse
}
var file_proto_identity_proto_depIdxs = []int32{
	1, // 0: p2panycast.identity.v1.ServiceCapability.allowed_policies:type_name -> p2panycast.identity.v1.AuthorizedPolicy
	2, // 1: p2panycast.identity.v1.ServiceCapability.allowed_ports:type_name -> p2panycast.identity.v1.PortRange
	0, // 2: p2panycast.identity.v1.IdentityClaims.role:type_name -> p2panycast.identity.v1.NodeRole
	3, // 3: p2panycast.identity.v1.IdentityClaims.capabilities:type_name -> p2panycast.identity.v1.ServiceCapability
	5, // 4: p2panycast.identity.v1.AuthHello.manifest:type_name -> p2panycast.identity.v1.SignedCapabilityManifest
	5, // 5: p2panycast.identity.v1.AuthResponse.manifest:type_name -> p2panycast.identity.v1.SignedCapabilityManifest
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_identity_proto_init() }
func file_proto_identity_proto_init() {
	if File_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_identity_proto_rawDesc), len(file_proto_identity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_identity_proto_goTypes,
		DependencyIndexes: file_proto_identity_proto_depIdxs,
		EnumInfos:         file_proto_identity_proto_enumTypes,
		MessageInfos:      file_proto_identity_proto_msgTypes,
	}.Build()
	File_proto_identity_proto = out.File
	file_proto_identity_proto_goTypes = nil
	file_proto_identity_proto_depIdxs = nil
}
